zone_id = "LfVkNe23oUNFKhUb48c9wm"
public_key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOc6u4WqsgzRsB+jrmiMnOT66LNeZgaRg43wofbX48pC arctair@clover"
remote_public_key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFCP4LX636dSJoOZGy6Rr22zZYEueUNbaTQR/QupEYKm arctair@clover"
